# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5beaae7551e7a4cb0c1a9ed83465b8ee9dd37f7b340f91e3a9e7a798c3d6c73060058980fc19b95373d592b800e79c6fba4bbbdbace50a079ffb413689b846

test:
  secret_key_base: 005c73fcf3167ff85dcf78daff0f95c6d49a3e41b9113ef8775a4398f368cf15a068c0c1065118324d28527437e1545196eca5ca548ffae1f313eee7a0235b04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
